### ISSUE TITLE
query_rec_ids.setdefault(s.id, list()).append(s) #AttributeError: 'str' object has no attribute 'id'

### ISSUE THREAD

**Issue by vmkalbskopf** [jvrana/pyblast2#1]
Hi there

I loaded my queries and reference database by: 
````
queries = make_linear(load_fasta_glob("*.fasta"))
subject = make_linear(load_fasta_glob("ref.fasta"))
````
Then I iterate over the records list in a loop, and try to blast each record against the ref like this:
````
for i in queries:
    print(i)
    blast = BioBlast(subject, i)
    results = blast.blastn()
    print(results)
````

The first record prints, but then the blast fails and throws this error:

````
ID: 102-11C_S3_L001_HtScaffold0130:30543-31089
Name: 102-11C_S3_L001_HtScaffold0130:30543-31089
Description: 102-11C_S3_L001_HtScaffold0130:30543-31089
Number of features: 0
/topology=linear
Seq('ATGGCTCGAAGGTATGACAGTAGAACTACAACGTTTTCACCTGAAGGGCGATTA...TAG', SingleLetterAlphabet())
Traceback (most recent call last):
  File "./all.py", line 33, in <module>
    blast = BioBlast(subject, i)
  File "/home/victor/anaconda3/lib/python3.7/site-packages/pyblast/blast/blast.py", line 444, in __init__
    self._check_records(subjects, queries)
  File "/home/victor/anaconda3/lib/python3.7/site-packages/pyblast/blast/blast.py", line 487, in _check_records
    self._check_duplicate_records(queries, subjects)
  File "/home/victor/anaconda3/lib/python3.7/site-packages/pyblast/blast/blast.py", line 497, in _check_duplicate_records
    query_rec_ids.setdefault(s.id, list()).append(s)
AttributeError: 'str' object has no attribute 'id'
````
Am I doing something wrong?

**Comment by vmkalbskopf** [comment]
I got around this issue by manually creating a SeqRecord in the loop. It's a hack though.

````
    rec = [
    SeqRecord(Seq(str(i.seq)),
    id=i.id,
    name=i.name,
    description=i.description)
    ]
    rec = make_linear(rec)
````
